name: engine

on: [push]

env:
  BUILD_TARGET: RELEASE

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Update Packages
      shell: bash
      run: sudo apt update -y

    - name: Install Packages
      shell: bash
      run: sudo apt install build-essential cmake libgl-dev libglew-dev libxrandr-dev libxinerama-dev libxcursor-dev -y

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure CMake
      shell: bash
      working-directory: build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TARGET

    - name: Build
      working-directory: build
      shell: bash
      run: cmake --build . --config $BUILD_TARGET